// Auto-generated by the FocusBook desktop app.
//
// On startup (and again just before it reveals this folder), the app overwrites
// this file with the real pairing token so that loading the unpacked extension
// connects automatically — no copy/paste. Until the app stamps it, the value
// below is an empty placeholder and the extension falls back to the manual
// token entry on its options page.
//
// Do not edit by hand; your changes will be overwritten.
globalThis.FOCUSBOOK_BUNDLED_TOKEN = ''
